[package]
license = "MIT OR Apache-2.0"
name = "demo"
version = "0.1.0"

[dependencies.stm32f103xx]
version = "0.7.5"
features = ["rt"]

[dependencies.cortex-m-rt]
features = ["abort-on-panic"]
version = "0.3.6"

[profile.release]
debug = true